#!/bin/tcsh

set njobs           = 100
set nevents         = 500
set minPtBin        = 1
set maxPtBin        = 7

set ptBin = $minPtBin

while ($ptBin <= $maxPtBin)

	./qsub_HLTAnalyzeRelValQCD 1 ${njobs} ${nevents} ${ptBin} hltWithoutLeptons
	
	@ ptBin = $ptBin + 1

end
