#!/bin/tcsh

set njobs           = 50
set nevents         = 1000
set minPtBin        = 1
set maxPtBin        = 5
set minJetThreshold = 20
set maxJetThreshold = 20

set ptBin = $minPtBin
set jetThreshold = $minJetThreshold

while ($ptBin <= $maxPtBin)

	set jetThreshold = $minJetThreshold

	while ($jetThreshold <= $maxJetThreshold)

		./qsub_AnalyzeRelValQCD 1 ${njobs} ${nevents} ${jetThreshold} ${ptBin} relValQCD
	
		@ jetThreshold = $jetThreshold + 1 

	end

	@ ptBin = $ptBin + 1

end
