#!/bin/tcsh

cd /uscms/home/eberry/TowerAlgo/CMSSW_2_2_7/src/Producers/CaloTowersFromTrigPrimsCreator/pionGun/RAW-DIGI-RECO

source /uscms/home/eberry/.tcshrc

eval `scramv1 runtime -csh`

./qsub_CentralPionGun_RAW-DIGI-RECO_ALL
./qsub_ForwardPionGun_RAW-DIGI-RECO_ALL
./qsub_MiddlePionGun_RAW-DIGI-RECO_ALL
