#!/bin/tcsh

cd /uscms/home/eberry/TowerAlgo/CMSSW_2_2_7/src/Producers/CaloTowersFromTrigPrimsCreator/pionGun/GEN-SIM-DIGI-RAW

source /uscms/home/eberry/.tcshrc

eval `scramv1 runtime -csh`

./qsub_CentralPionGun_GEN-SIM-DIGI-RAW_ALL
./qsub_ForwardPionGun_GEN-SIM-DIGI-RAW_ALL
./qsub_MiddlePionGun_GEN-SIM-DIGI-RAW_ALL
