#!/bin/tcsh

set njobs           = 10
set nevents         = 10000
set minPtBin        = 1
set maxPtBin        = 13
set minJetThreshold = 3
set maxJetThreshold = 30

set ptBin = $minPtBin
set jetThreshold = $minJetThreshold

while ($ptBin <= $maxPtBin)

	set jetThreshold = $minJetThreshold

	while ($jetThreshold <= $maxJetThreshold)

		./qsub_ReRunL1AndHLTOnMC_FAST 1 ${njobs} ${nevents} ${jetThreshold} ${ptBin} withCorJets
	
		@ jetThreshold = $jetThreshold + 1 

	end

	@ ptBin = $ptBin + 1

end
