#!/bin/tcsh

set work_dir = $PWD
set begin = 0
set end = 0
set ptBin = 0
set numjobs = 0
set numevents = 0

setenv CMSSW_BASE /uscms/home/eberry/CMSSW_2_2_3/

if ($#argv == 6) then
    echo 'Setting working directory to' $PWD
    set begin = $1
    set end = $2
    set ptBin = $3
    set numjobs = $4
    set numevents = $5
    set suffix = $6
else if( $#argv == 7 ) then
    if ( -d $1 ) then
	set work_dir = $1
	set begin = $2
	set end = $3
	set ptBin = $4
	set numjobs = $5
	set numevents = $6
	set suffix = $7
    else
	echo "Error! $1 is not a directory, exiting!"
	exit 1
    endif

else 
    echo "Usage: $0 <work_dir> <low_threshold> <high_threshold> <ptBin> <njobs> <neventsPerJob> <rootFileSuffix> OR"
    echo "If desired work directory is the current one, omit directory argument."
    echo "The script assumes there is a sub-directory called log/ in the designated work dir."
    exit 1
endif

cd $work_dir

if (! -e qrun_ReRunL1AndHLTOnMC ) then
    echo "Warning! Could not find executable qrun_ReRunL1AndHLTOnMC, script will exit"
    exit 1
endif
if (! -e log ) then
    echo "Warning! Could not find log directory - please create."
    exit 1
endif

echo "Notifications will be sent to $user@fnal.gov"

set threshold = $begin
set job = 1


while ($threshold <= $end)

while ($job <= $numjobs) 

echo Argument string is $work_dir $threshold $ptBin $job $numevents $suffix

cat > reRunAndHLTOnMC_ptBin${ptBin}_${threshold}_${job}_condor<<EOF
universe = vanilla
Executable = ${CMSSW_BASE}/src/Analyzers/L1SkimAnalyzer/test/qrun_ReRunL1AndHLTOnMC
Requirements = Memory >= 199 &&OpSys == "LINUX" && (Arch != "DUMMY" )
ShouldTransferFiles = YES
WhenToTransferOutput = ON_EXIT
Output = ${CMSSW_BASE}/src/Analyzers/L1SkimAnalyzer/test/log/reRunAndHLTOnMC_ptBin${ptBin}_threshold${threshold}_job${job}_\$(Cluster)_\$(Process).stdout

Error = ${CMSSW_BASE}/src/Analyzers/L1SkimAnalyzer/test/log/reRunAndHLTOnMC_ptBin${ptBin}_threshold${threshold}_job${job}_\$(Cluster)_\$(Process).stderr
Log = ${CMSSW_BASE}/src/Analyzers/L1SkimAnalyzer/test/log/reRunAndHLTOnMC_ptBin${ptBin}_threshold${threshold}_job${job}_\$(Cluster)_\$(Process).log
notify_user = ${user}@FNAL.GOV
Arguments = $work_dir $threshold $ptBin $job $numevents $suffix
Queue 1
EOF

condor_submit reRunAndHLTOnMC_ptBin${ptBin}_${threshold}_${job}_condor

@ job = ($job + 1)

end

@ threshold = ($threshold + 1)

end

echo This is the end
