#!/bin/tcsh

## Scans over digis in a given data set

cd /uscms/home/eberry/CMSSW_3_1_0_pre1/src/Analyzers/HcalDigiAnalyzer/test/
source /uscmst1/prod/sw/cms/cshrc uaf
eval `scram runtime -csh`

#source ${HOME}/.tcshrc
#echo "CMSSW_BASE = ${CMSSW_BASE}"
#cd ${CMSSW_BASE}/src/Analyzers/HcalDigiAnalyzer/test
#cmsenv

## For getting info from simulation
set hcalDigiTag     = ""
##set hcalDigiTag     = ${1}
set suffix          = "data"
set caloTowerTag    = "towerMaker"
set hcalTrigPrimTag = "simHcalTriggerPrimitiveDigis"
set fileName        = "extractDigisAndAnalyze_MikesDigis_${suffix}_cfg.py"

cat > ${fileName}<<EOF
import FWCore.ParameterSet.Config as cms

process = cms.Process("MyHcalDigiAnalyzer")
process.load('FWCore/MessageService/MessageLogger_cfi')
process.load("Configuration.StandardSequences.Services_cff")
process.load("Configuration.EventContent.EventContent_cff")

##-----------------------------------------------
## Input number of events 
##-----------------------------------------------

process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(-1)
)

##-----------------------------------------------
## Input Global Tag
##-----------------------------------------------

process.load("Configuration.StandardSequences.Geometry_cff")
process.load("Configuration.StandardSequences.FrontierConditions_GlobalTag_cff")
process.GlobalTag.globaltag = 'STARTUP_30X::All'

##-----------------------------------------------
## Source goes here.  
##-----------------------------------------------

process.source = cms.Source("PoolSource",
    skipEvents = cms.untracked.uint32(0),    
    fileNames = cms.untracked.vstring(
	'file:///uscms/home/eberry/mikeh_data/promptRecoHCalNoise.root'
    )
)

##-----------------------------------------------
## Unpack the digis
##-----------------------------------------------

process.load("Configuration.StandardSequences.RawToDigi_Data_cff")
process.unpack = cms.Path(process.RawToDigi)

##-----------------------------------------------
## Declare analyzer objects for each DataFrame type
##-----------------------------------------------

process.hbDigiAnalyzer          = cms.EDAnalyzer("HBHEDigiAnalyzer", 
	hcalDigiTag             = cms.untracked.InputTag ("hcalDigis"),
	caloTowerTag            = cms.untracked.InputTag ("${caloTowerTag}"),
	hcalTrigPrimTag         = cms.untracked.InputTag ("${hcalTrigPrimTag}"),
	outPath                 = cms.untracked.string   ("${HOME}/data/"),
	outSuffix               = cms.untracked.string   ("_${suffix}"),
	subdetName              = cms.untracked.string   ("HB"),
	useEventList            = cms.untracked.bool     (True)
)			        
				    
process.heDigiAnalyzer          = cms.EDAnalyzer("HBHEDigiAnalyzer",		
	hcalDigiTag             = cms.untracked.InputTag ("hcalDigis"),
	caloTowerTag            = cms.untracked.InputTag ("${caloTowerTag}"),
	hcalTrigPrimTag         = cms.untracked.InputTag ("${hcalTrigPrimTag}"),
	outPath                 = cms.untracked.string   ("${HOME}/data/"),
	outSuffix               = cms.untracked.string   ("_${suffix}"),
	subdetName              = cms.untracked.string   ("HE"),
	useEventList            = cms.untracked.bool     (True)
)			        
			        
process.hoDigiAnalyzer          = cms.EDAnalyzer("HODigiAnalyzer",
	hcalDigiTag             = cms.untracked.InputTag ("hcalDigis"),
	caloTowerTag            = cms.untracked.InputTag ("${caloTowerTag}"),
	hcalTrigPrimTag         = cms.untracked.InputTag ("${hcalTrigPrimTag}"),
	outPath                 = cms.untracked.string   ("${HOME}/data/"),
	outSuffix               = cms.untracked.string   ("_${suffix}"),
	subdetName              = cms.untracked.string   ("HO"),
	useEventList            = cms.untracked.bool     (True)
)			        
			        
process.hfDigiAnalyzer          = cms.EDAnalyzer("HFDigiAnalyzer",
	hcalDigiTag             = cms.untracked.InputTag ("hcalDigis"),
	caloTowerTag            = cms.untracked.InputTag ("${caloTowerTag}"),
	hcalTrigPrimTag         = cms.untracked.InputTag ("${hcalTrigPrimTag}"),
	outPath                 = cms.untracked.string   ("${HOME}/data/"),
	outSuffix               = cms.untracked.string   ("_${suffix}"),
	subdetName              = cms.untracked.string   ("HF"),
        useEventList            = cms.untracked.bool     (True),
	doRecHitPulseCorrection = cms.untracked.bool     (False)
)


process.analyze = cms.Path(
		  process.hbDigiAnalyzer
		* process.heDigiAnalyzer
	        * process.hoDigiAnalyzer
		* process.hfDigiAnalyzer
		)

process.schedule = cms.Schedule()
process.schedule.append(process.unpack )
process.schedule.append(process.analyze)

EOF

cmsRun ${fileName}

