#!/bin/tcsh

set work_dir = $PWD
set ptBin = 0
set numjobs = 0
set numevents = 0

setenv CMSSW_BASE /uscms/home/eberry/CMSSW_2_2_3/

if ($#argv == 4) then
    echo 'Setting working directory to' $PWD
    set ptBin = $1
    set numjobs = $2
    set numevents = $3
    set suffix = $4
else if( $#argv == 5 ) then
    if ( -d $1 ) then
	set work_dir = $1
	set ptBin = $2
	set numjobs = $3
	set numevents = $4
	set suffix = $5
    else
	echo "Error! $1 is not a directory, exiting!"
	exit 1
    endif 

else 
    echo "Usage: $0 <work_dir> <ptBin> <njobs> <neventsPerJob> <rootFileSuffix> OR"
    echo "If desired work directory is the current one, omit directory argument."
    echo "The script assumes there is a sub-directory called log/ in the designated work dir."
    exit 1
endif

cd $work_dir

if (! -e qrun_FastSim ) then
    echo "Warning! Could not find executable qrun_FastSim, script will exit"
    exit 1
endif
if (! -e log ) then
    echo "Warning! Could not find log directory - please create."
    exit 1
endif

echo "Notifications will be sent to $user@fnal.gov"
 
set job = 1


while ($job <= $numjobs) 

echo Argument string is $work_dir $ptBin $job $numevents $suffix

cat > fastSim_ptBin${ptBin}_${job}_condor<<EOF
universe = vanilla
Executable = ${CMSSW_BASE}/src/Analyzers/L1SkimAnalyzer/test/qrun_FastSim
Requirements = Memory >= 199 &&OpSys == "LINUX" && (Arch != "DUMMY" )
ShouldTransferFiles = YES
WhenToTransferOutput = ON_EXIT
Output = ${CMSSW_BASE}/src/Analyzers/L1SkimAnalyzer/test/log/fastSim_ptBin${ptBin}_job${job}_\$(Cluster)_\$(Process).stdout

Error = ${CMSSW_BASE}/src/Analyzers/L1SkimAnalyzer/test/log/fastSim_ptBin${ptBin}_job${job}_\$(Cluster)_\$(Process).stderr
Log = ${CMSSW_BASE}/src/Analyzers/L1SkimAnalyzer/test/log/fastSim_ptBin${ptBin}_job${job}_\$(Cluster)_\$(Process).log
notify_user = ${user}@FNAL.GOV
Arguments = $work_dir $ptBin $job $numevents $suffix
Queue 1
EOF

condor_submit fastSim_ptBin${ptBin}_${job}_condor

@ job = ($job + 1)

end

echo This is the end
