#!/bin/bash

## Set release base and version
rundir="/uscms/home/eberry/3DayLifetime/Crab/OfficialCSCSample/"
logdir="${rundir}/log/"
datapath=""

MY_RELEASE_BASE="/uscms/home/eberry/MuonMomentumStudy/"
CMSSW_VERSION="CMSSW_3_2_4"
TEST="false"
export HOME=/uscms/home/${USER}

## Set variables 
eventsPerJob="1000"
numTotalEvents="5000000"
## numJobs="1"
## eventsPerJob="10"
suffix="_NewField_MuMinus_OfficialSample_Full"
verbose=""

if [ $TEST == "true" ]; then
    verbose="process.csctfMuonPtAnalyzer.Verbose = True"
    suffix="_TEST"
fi

## Make the run dir if it doesn't exist ...
if [ ! -d ${rundir} ]; then
    mkdir -p ${rundir} || exit
fi
cd ${rundir} || exit

if [ ! -d ${logdir} ]; then
    mkdir -p ${logdir} || exit
fi

cd $rundir

## Load the environment
source /uscmst1/prod/sw/cms/bashrc prod
source /uscmst1/prod/grid/CRAB/crab.csh
source /uscmst1/prod/grid/CRAB_2_6_3/crab.sh


## Set python file name
pythonFile="CSCMuonGun_FullCopy_${suffix}_cfg.py"
outputFile="CSCMuonGun_FullCopy_${suffix}.root"

## Tell the log file what you're going to do
echo "I am going to do some binning"
echo "I am using CMSSW version: ${CMSSW_VERSION}"
echo "I am making python cfg file: ${pythonFile}"
echo "I am using the suffix ${suffix}"

cat > ${pythonFile}<<EOF

import FWCore.ParameterSet.Config as cms
process = cms.Process ("AnalyzeMuonPt")

process.load('Configuration/StandardSequences/Services_cff')
process.load('FWCore/MessageService/MessageLogger_cfi')
process.load('Configuration/StandardSequences/MixingNoPileUp_cff')
process.load('Configuration/StandardSequences/GeometryIdeal_cff')
process.load('Configuration/StandardSequences/MagneticField_38T_ToscaMap090322_cff')
process.load('Configuration/StandardSequences/Generator_cff')
process.load('Configuration/StandardSequences/VtxSmearedEarly10TeVCollision_cff')
process.load('Configuration/StandardSequences/Sim_cff')
process.load('Configuration/StandardSequences/Digi_cff')
process.load('Configuration/StandardSequences/SimL1Emulator_cff')
process.load('Configuration/StandardSequences/DigiToRaw_cff')
process.load('Configuration/StandardSequences/RawToDigi_cff')
process.load('Configuration/StandardSequences/Reconstruction_cff')
process.load('Configuration/StandardSequences/EndOfProcess_cff')
process.load('Configuration/EventContent/EventContent_cff')

## Start message logger
MessageLogger = cms.Service("MessageLogger")
 
## 'dcache:/pnfs/cms/WAX/resilient/eberry/CMSSW_ROOT_Files/ParticleGun/CSCMuonGun/GEN-SIM-DIGI-L1_WithDT/CSCMuonGun_STARTUP31X_V4_GEN-SIM-DIGI-L1_job1_62500events_80.0-90.0GeV-PtBin26_0-140GeV.root'

## Configure the source
process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1))
process.source = cms.Source("PoolSource",
  fileNames = cms.untracked.vstring(),
  duplicateCheckMode = cms.untracked.string('noDuplicateCheck')
)

process.copy = cms.OutputModule("PoolOutputModule",                               
  outputCommands = cms.untracked.vstring( 'keep *' ),
  fileName = cms.untracked.string('${outputFile}')
)

## Configure paths
process.COPY = cms.EndPath( process.copy )

## Schedule paths
process.schedule = cms.Schedule()
process.schedule.append( process.COPY )
 
EOF

if [ $TEST == "true" ]; then
    cmsRun ${pythonFile}
    exit
fi

crabFile=crab.cfg
cat > ${crabFile} <<EOF
[CRAB]
jobtype = cmssw
scheduler = glite
server_name = bari

[CMSSW]
datasetpath=/SingleMuonMinusOneOverPt_NewField/Summer09-MC_31X_V8-v1/GEN-SIM-DIGI-RAW-RECO
pset=${pythonFile}
events_per_job = ${eventsPerJob}
total_number_of_events = ${numTotalEvents}
output_file = ${outputFile}

[USER]
eMail = Edmund.Berry@gmail.com
copy_data = 1
storage_element = T3_US_FNALLPC
user_remote_dir = OfficialSampleFull/
return_data = 0
logdir=${logdir}

[GRID]
##  Black and White Lists management:
## By ComputingElement
## ce_black_list = ucsd
se_white_list = T1_IT_CNAF, T2_ES_CIEMAT

EOF

crab -create
crab -submit
