#!/bin/tcsh

set njobs           = 50
set nevents         = 20

set LAUNCH_DIR = $PWD
set RELEASE_DIR = /uscms/home/eberry/TowerAlgo/CMSSW_2_2_7/src/

## cd RELEASE_DIR 
## tar cf Release.tar Analyzers Producers Geometry
## cd LAUNCH_DIR

./qsub_MuonGun_RAW-DIGI-RECO 1 ${njobs} ${nevents} ""

