#!/bin/tcsh

cd ${CMSSW_BASE}/src/Analyzers/DijetAnalyzer/test
cmsenv

setenv DIJETbit $1
setenv CRUZETbit $2

if ($DIJETbit == 0) setenv sourceName "nuGun"
if ($DIJETbit == 1) setenv sourceName "diJet"

if ($CRUZETbit == 0) setenv methodName "Gauss"
if ($CRUZETbit == 1) setenv methodName "CRUZET"

cat > myAnalyzer_${sourceName}_${methodName}.cfg<<EOF

process Demo =  {

	## Set number of events
	untracked PSet maxEvents = {untracked int32 input = 2000}

	## For HCAL sim
	include "Analyzers/DijetAnalyzer/data/RecommendedHcalConditions.cff"
	include "Configuration/StandardSequences/data/FakeConditions.cff"

	## Source data files
	include "Analyzers/DijetAnalyzer/data/dataFiles_${sourceName}_${methodName}_test.cff"
	
	service = MessageLogger {}
	
	module dijetAnalyzer = DijetAnalyzer {
		untracked string rootFile = "data/DijetAnalyzerOutput_${methodName}_${sourceName}.root"
	}
     
	path analyze = {dijetAnalyzer}

	schedule = {analyze}
}
EOF

cd ${CMSSW_BASE}/src/Analyzers/DijetAnalyzer/

cmsRun test/myAnalyzer_${sourceName}_${methodName}.cfg
