#!/bin/tcsh

cd /uscms/home/eberry/TowerAlgo/CMSSW_2_2_7/src/Producers/CaloTowersFromTrigPrimsCreator/electronGun/ANA

source /uscms/home/eberry/.tcshrc

eval `scramv1 runtime -csh`

./qsub_CentralElectronGun_ANA_ALL
./qsub_ForwardElectronGun_ANA_ALL
./qsub_MiddleElectronGun_ANA_ALL
