#!/bin/tcsh

cd /uscms/home/eberry/TowerAlgo/CMSSW_2_2_7/src/Producers/CaloTowersFromTrigPrimsCreator/pionGun/ANA

source /uscms/home/eberry/.tcshrc

eval `scramv1 runtime -csh`

./qsub_CentralPionGun_ANA_ALL
./qsub_ForwardPionGun_ANA_ALL
./qsub_MiddlePionGun_ANA_ALL
