#!/bin/tcsh

set njobs           = 1
set nevents         = 1000

set LAUNCH_DIR = $PWD
set RELEASE_DIR = /uscms/home/eberry/TowerAlgo/CMSSW_2_2_7/src/

## cd RELEASE_DIR 
## tar cf Release.tar Analyzers Producers Geometry
## cd LAUNCH_DIR

./qsub_PionGun_ANA 1 ${njobs} ${nevents} ""

