#!/bin/tcsh

cd /uscms/home/eberry/TowerAlgo/CMSSW_2_2_7/src/Producers/CaloTowersFromTrigPrimsCreator/electronGun/GEN-SIM-DIGI-RAW

source /uscms/home/eberry/.tcshrc

eval `scramv1 runtime -csh`

./qsub_CentralElectronGun_GEN-SIM-DIGI-RAW_ALL
./qsub_ForwardElectronGun_GEN-SIM-DIGI-RAW_ALL
./qsub_MiddleElectronGun_GEN-SIM-DIGI-RAW_ALL
